# Generated by Django 3.1 on 2020-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_page',
            field=models.BooleanField(default=True),
        ),
    ]
