# Generated by Django 3.1 on 2020-12-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201227_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='cash_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='robokassa_payment',
            field=models.BooleanField(default=False),
        ),
    ]
