# Generated by Django 3.1 on 2020-12-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201228_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orderitem'),
        ),
    ]
