# Generated by Django 3.1 on 2020-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shippingaddress_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='products',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='products',
            field=models.ManyToManyField(null=True, to='home.OrderItem'),
        ),
    ]
