# Generated by Django 3.1 on 2020-12-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
