# Generated by Django 3.1 on 2020-12-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_orderadminpanel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderadminpanel',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderadminpanel',
            name='orders',
            field=models.ManyToManyField(null=True, to='home.OrderItem'),
        ),
    ]
