# Generated by Django 3.1 on 2020-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201230_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderadminpanel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderadminpanel',
            name='sec_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='cash_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='robokassa_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
