# Generated by Django 3.1 on 2020-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201230_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadminpanel',
            name='address_2',
            field=models.CharField(blank=True, default='address_2', max_length=500),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='company_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='phone_2',
            field=models.CharField(blank=True, default='phone_2', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='sec_name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
