# Generated by Django 3.1 on 2020-12-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201230_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadminpanel',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderadminpanel',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
