# Generated by Django 3.1 on 2021-01-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201230_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAdminPanel',
        ),
    ]
