# Generated by Django 3.1 on 2021-01-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_shippingaddress_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(choices=[('New', 'Новое!'), ('Delivery', 'Доставка'), ('Delivered', 'Доставлено')], default='New', max_length=300),
        ),
    ]
