# Generated by Django 3.1 on 2021-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_shippingaddress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(choices=[('Новое', 'Новое!'), ('Доставка', 'Доставка'), ('Доставлено', 'Доставлено')], default='New', max_length=300),
        ),
    ]
